# Generated by Django 3.0.6 on 2020-05-04 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField()),
                ('description', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(null=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recommended', models.PositiveIntegerField(default=0)),
                ('not_recommended', models.PositiveIntegerField(default=0)),
                ('required_amount', models.PositiveIntegerField()),
                ('collected_amount', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
