# Generated by Django 3.0.6 on 2020-05-06 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20200506_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='Default', max_length=150),
            preserve_default=False,
        ),
    ]
